"""Comprehensive cross-platform market name aliases for prediction market matching.

Maps abbreviations, nicknames, city names, and team names to canonical forms
to improve cross-platform matching between Kalshi and Polymarket.

Over 500 alias entries covering NBA, NFL, NHL, MLB, MLS, EPL, La Liga,
Bundesliga, Serie A, Ligue 1, NCAA, crypto, politics, and entertainment.

Rules applied during construction:
- Word boundaries (\\b) prevent partial matches
- re.IGNORECASE on natural-language terms; case-sensitive for acronyms
- Negative lookahead where needed (e.g., "Inter" must not match "Inter Miami")
- Ambiguous mappings skipped (e.g., "United" alone, "Los Angeles" alone)
- Each (pattern, replacement) tuple is applied sequentially via _expand_abbreviations()
"""

from __future__ import annotations

import re

# (pattern, replacement) -- applied sequentially via _expand_abbreviations()
ABBREVIATION_MAP: list[tuple[re.Pattern, str]] = [
    # ========================================================================
    #  NBA (30 teams)
    # ========================================================================

    # -- Abbreviation -> Full --
    (re.compile(r"\bOKC\b"), "Oklahoma City Thunder"),
    (re.compile(r"\bNYK\b"), "New York Knicks"),
    (re.compile(r"\bGSW\b"), "Golden State Warriors"),
    (re.compile(r"\bSAS\b"), "San Antonio Spurs"),
    (re.compile(r"\bNOP\b"), "New Orleans Pelicans"),
    (re.compile(r"\bLAL\b"), "Los Angeles Lakers"),
    (re.compile(r"\bPHX\b"), "Phoenix Suns"),
    (re.compile(r"\bDAL\b"), "Dallas Mavericks"),
    (re.compile(r"\bPOR\b"), "Portland Trail Blazers"),
    (re.compile(r"\bMIN\b(?!\s+(?:Vikings|United))", re.IGNORECASE), "Minnesota Timberwolves"),
    (re.compile(r"\bSAC\b"), "Sacramento Kings"),
    (re.compile(r"\bCHA\b"), "Charlotte Hornets"),
    (re.compile(r"\bWAS\b(?!\s+(?:Commanders))", re.IGNORECASE), "Washington Wizards"),
    (re.compile(r"\bIND\b(?!\s+(?:iana))", re.IGNORECASE), "Indiana Pacers"),

    # -- Nickname -> Full --
    (re.compile(r"\bSixers\b", re.IGNORECASE), "Philadelphia 76ers"),
    (re.compile(r"\b76ers\b", re.IGNORECASE), "Philadelphia 76ers"),
    (re.compile(r"\bCavs\b", re.IGNORECASE), "Cleveland Cavaliers"),
    (re.compile(r"\bMavs\b", re.IGNORECASE), "Dallas Mavericks"),
    (re.compile(r"\bBlazers\b", re.IGNORECASE), "Portland Trail Blazers"),
    (re.compile(r"\bT-Wolves\b", re.IGNORECASE), "Minnesota Timberwolves"),
    (re.compile(r"\bTimberwolves\b", re.IGNORECASE), "Minnesota Timberwolves"),
    (re.compile(r"\bDubs\b", re.IGNORECASE), "Golden State Warriors"),
    (re.compile(r"\bLake Show\b", re.IGNORECASE), "Los Angeles Lakers"),
    (re.compile(r"\bRip City\b", re.IGNORECASE), "Portland Trail Blazers"),

    # -- Multi-word city/qualifier -> Full --
    (re.compile(r"\bLA Clippers\b", re.IGNORECASE), "Los Angeles Clippers"),
    (re.compile(r"\bLA Lakers\b", re.IGNORECASE), "Los Angeles Lakers"),
    (re.compile(r"\bPro Basketball\b", re.IGNORECASE), "NBA"),

    # -- City name -> Full (only where unambiguous within NBA context) --
    (re.compile(r"\bCleveland\b(?!\s+(?:Browns|Guardians|Cavaliers))", re.IGNORECASE), "Cleveland Cavaliers"),
    (re.compile(r"\bMilwaukee\b(?!\s+(?:Brewers|Bucks))", re.IGNORECASE), "Milwaukee Bucks"),
    (re.compile(r"\bPhoenix\b(?!\s+(?:Suns|Mercury))", re.IGNORECASE), "Phoenix Suns"),
    (re.compile(r"\bSacramento\b(?!\s+(?:Kings|Republic))", re.IGNORECASE), "Sacramento Kings"),
    (re.compile(r"\bOrlando\b(?!\s+(?:Magic|City))", re.IGNORECASE), "Orlando Magic"),
    (re.compile(r"\bMemphis\b(?!\s+(?:Grizzlies|901))", re.IGNORECASE), "Memphis Grizzlies"),
    (re.compile(r"\bSan Antonio\b(?!\s+(?:Spurs|FC))", re.IGNORECASE), "San Antonio Spurs"),
    (re.compile(r"\bNew Orleans\b(?!\s+(?:Pelicans|Saints))", re.IGNORECASE), "New Orleans Pelicans"),

    # -- Unique mascot -> Full --
    (re.compile(r"\bCavaliers\b", re.IGNORECASE), "Cleveland Cavaliers"),
    (re.compile(r"\bThunder\b(?!\s+Bay)", re.IGNORECASE), "Oklahoma City Thunder"),
    (re.compile(r"\bKnicks\b", re.IGNORECASE), "New York Knicks"),
    (re.compile(r"\bNets\b(?!\s+(?:flix|work))", re.IGNORECASE), "Brooklyn Nets"),
    (re.compile(r"\bRaptors\b", re.IGNORECASE), "Toronto Raptors"),
    (re.compile(r"\bCeltics\b", re.IGNORECASE), "Boston Celtics"),
    (re.compile(r"\bHeat\b(?!\s+(?:wave|map|stroke))", re.IGNORECASE), "Miami Heat"),
    (re.compile(r"\bMagic\b(?!\s+(?:Johnson|Kingdom|the))", re.IGNORECASE), "Orlando Magic"),
    (re.compile(r"\bPacers\b", re.IGNORECASE), "Indiana Pacers"),
    (re.compile(r"\bWizards\b", re.IGNORECASE), "Washington Wizards"),
    (re.compile(r"\bBulls\b(?!\s+(?:eye|hit))", re.IGNORECASE), "Chicago Bulls"),
    (re.compile(r"\bBucks\b", re.IGNORECASE), "Milwaukee Bucks"),
    (re.compile(r"\bPistons\b", re.IGNORECASE), "Detroit Pistons"),
    (re.compile(r"\bHawks\b(?!\s+(?:Bay|Tony))", re.IGNORECASE), "Atlanta Hawks"),
    (re.compile(r"\bGrizzlies\b", re.IGNORECASE), "Memphis Grizzlies"),
    (re.compile(r"\bPelicans\b", re.IGNORECASE), "New Orleans Pelicans"),
    (re.compile(r"\bNuggets\b", re.IGNORECASE), "Denver Nuggets"),
    (re.compile(r"\bWarriors\b(?!\s+FC)", re.IGNORECASE), "Golden State Warriors"),
    (re.compile(r"\bLakers\b", re.IGNORECASE), "Los Angeles Lakers"),
    (re.compile(r"\bClippers\b", re.IGNORECASE), "Los Angeles Clippers"),
    (re.compile(r"\bTrail Blazers\b", re.IGNORECASE), "Portland Trail Blazers"),
    (re.compile(r"\bSuns\b", re.IGNORECASE), "Phoenix Suns"),
    (re.compile(r"\bKings\b(?!\s+(?:League|XI|Cup|of))", re.IGNORECASE), "Sacramento Kings"),
    (re.compile(r"\bJazz\b(?!\s+(?:music|festival))", re.IGNORECASE), "Utah Jazz"),
    (re.compile(r"\bRockets\b", re.IGNORECASE), "Houston Rockets"),
    (re.compile(r"\bHornets\b(?!\s+(?:Charlotte))", re.IGNORECASE), "Charlotte Hornets"),

    # ========================================================================
    #  NFL (32 teams)
    # ========================================================================

    # -- Abbreviation -> Full --
    (re.compile(r"\bKC\b(?!\s+(?:Current|Royals))", re.IGNORECASE), "Kansas City Chiefs"),
    (re.compile(r"\bGB\b"), "Green Bay Packers"),
    (re.compile(r"\bTB\b(?!\s+(?:12|Lightning|Rays))", re.IGNORECASE), "Tampa Bay Buccaneers"),
    (re.compile(r"\bNE\b(?!\s+(?:Patriots|Revolution))", re.IGNORECASE), "New England Patriots"),
    (re.compile(r"\bJAX\b"), "Jacksonville Jaguars"),
    (re.compile(r"\bLV\b"), "Las Vegas Raiders"),
    (re.compile(r"\bARI\b"), "Arizona Cardinals"),
    (re.compile(r"\bCIN\b"), "Cincinnati Bengals"),
    (re.compile(r"\bCLE\b"), "Cleveland Browns"),
    (re.compile(r"\bDEN\b"), "Denver Broncos"),
    (re.compile(r"\bHOU\b"), "Houston Texans"),
    (re.compile(r"\bTEN\b"), "Tennessee Titans"),
    (re.compile(r"\bPIT\b"), "Pittsburgh Steelers"),
    (re.compile(r"\bSF\b(?!\s+(?:Giants|49ers))", re.IGNORECASE), "San Francisco 49ers"),
    (re.compile(r"\bSEA\b"), "Seattle Seahawks"),
    (re.compile(r"\bBAL\b"), "Baltimore Ravens"),
    (re.compile(r"\bBUF\b"), "Buffalo Bills"),
    (re.compile(r"\bDET\b"), "Detroit Lions"),
    (re.compile(r"\bPHI\b"), "Philadelphia Eagles"),
    (re.compile(r"\bLAR\b"), "Los Angeles Rams"),
    (re.compile(r"\bNYG\b"), "New York Giants"),
    (re.compile(r"\bNYJ\b"), "New York Jets"),

    # -- Nickname -> Full --
    (re.compile(r"\bNiners\b", re.IGNORECASE), "San Francisco 49ers"),
    (re.compile(r"\b49ers\b", re.IGNORECASE), "San Francisco 49ers"),
    (re.compile(r"\bPackers\b", re.IGNORECASE), "Green Bay Packers"),
    (re.compile(r"\bPack\b(?!\s+(?:age|ed|ing))", re.IGNORECASE), "Green Bay Packers"),
    (re.compile(r"\bPats\b", re.IGNORECASE), "New England Patriots"),
    (re.compile(r"\bPatriots\b", re.IGNORECASE), "New England Patriots"),
    (re.compile(r"\bBucs\b", re.IGNORECASE), "Tampa Bay Buccaneers"),
    (re.compile(r"\bBuccaneers\b", re.IGNORECASE), "Tampa Bay Buccaneers"),
    (re.compile(r"\bBroncos\b", re.IGNORECASE), "Denver Broncos"),
    (re.compile(r"\bBengals\b", re.IGNORECASE), "Cincinnati Bengals"),
    (re.compile(r"\bSteelers\b", re.IGNORECASE), "Pittsburgh Steelers"),
    (re.compile(r"\bRavens\b", re.IGNORECASE), "Baltimore Ravens"),
    (re.compile(r"\bBills\b(?!\s+(?:of|Act|due))", re.IGNORECASE), "Buffalo Bills"),
    (re.compile(r"\bDolphins\b", re.IGNORECASE), "Miami Dolphins"),
    (re.compile(r"\bEagles\b(?!\s+(?:FC|Landing|Boy|Scout))", re.IGNORECASE), "Philadelphia Eagles"),
    (re.compile(r"\bCowboys\b", re.IGNORECASE), "Dallas Cowboys"),
    (re.compile(r"\bChiefs\b", re.IGNORECASE), "Kansas City Chiefs"),
    (re.compile(r"\bRaiders\b", re.IGNORECASE), "Las Vegas Raiders"),
    (re.compile(r"\bChargers\b", re.IGNORECASE), "Los Angeles Chargers"),
    (re.compile(r"\bSeahawks\b", re.IGNORECASE), "Seattle Seahawks"),
    (re.compile(r"\bRams\b(?!\s+(?:ey|gate))", re.IGNORECASE), "Los Angeles Rams"),
    (re.compile(r"\bBears\b(?!\s+(?:Ears|market|Stearns))", re.IGNORECASE), "Chicago Bears"),
    (re.compile(r"\bLions\b(?!\s+(?:Gate|King|of))", re.IGNORECASE), "Detroit Lions"),
    (re.compile(r"\bVikings\b", re.IGNORECASE), "Minnesota Vikings"),
    (re.compile(r"\bSaints\b", re.IGNORECASE), "New Orleans Saints"),
    (re.compile(r"\bFalcons\b", re.IGNORECASE), "Atlanta Falcons"),
    (re.compile(r"\bPanthers\b(?!\s+(?:FC|Florida))", re.IGNORECASE), "Carolina Panthers"),
    (re.compile(r"\bTitans\b", re.IGNORECASE), "Tennessee Titans"),
    (re.compile(r"\bTexans\b", re.IGNORECASE), "Houston Texans"),
    (re.compile(r"\bColts\b", re.IGNORECASE), "Indianapolis Colts"),
    (re.compile(r"\bJaguars\b", re.IGNORECASE), "Jacksonville Jaguars"),
    (re.compile(r"\bJags\b", re.IGNORECASE), "Jacksonville Jaguars"),
    (re.compile(r"\bJets\b(?!\s+(?:Blue|Private|Winnipeg))", re.IGNORECASE), "New York Jets"),
    (re.compile(r"\bGiants\b(?!\s+(?:SF|San|Causeway))", re.IGNORECASE), "New York Giants"),
    (re.compile(r"\bCommanders\b", re.IGNORECASE), "Washington Commanders"),
    (re.compile(r"\bBrowns\b", re.IGNORECASE), "Cleveland Browns"),
    (re.compile(r"\bCardinals\b(?!\s+(?:St|baseball|MLB))", re.IGNORECASE), "Arizona Cardinals"),

    # -- City -> Full (unambiguous NFL cities) --
    (re.compile(r"\bGreen Bay\b", re.IGNORECASE), "Green Bay Packers"),
    (re.compile(r"\bJacksonville\b(?!\s+(?:Jaguars|State))", re.IGNORECASE), "Jacksonville Jaguars"),
    (re.compile(r"\bPittsburgh\b(?!\s+(?:Steelers|Penguins|Pirates))", re.IGNORECASE), "Pittsburgh Steelers"),
    (re.compile(r"\bBuffalo\b(?!\s+(?:Bills|Sabres))", re.IGNORECASE), "Buffalo Bills"),
    (re.compile(r"\bBaltimore\b(?!\s+(?:Ravens|Orioles))", re.IGNORECASE), "Baltimore Ravens"),
    (re.compile(r"\bCincinnati\b(?!\s+(?:Bengals|Reds))", re.IGNORECASE), "Cincinnati Bengals"),
    (re.compile(r"\bSeattle\b(?!\s+(?:Seahawks|Kraken|Mariners|Sounders))", re.IGNORECASE), "Seattle Seahawks"),
    (re.compile(r"\bLas Vegas\b(?!\s+(?:Raiders|Aces|Knights))", re.IGNORECASE), "Las Vegas Raiders"),
    (re.compile(r"\bTampa Bay\b(?!\s+(?:Buccaneers|Lightning|Rays))", re.IGNORECASE), "Tampa Bay Buccaneers"),
    (re.compile(r"\bIndianapolis\b(?!\s+(?:Colts|500))", re.IGNORECASE), "Indianapolis Colts"),

    # ========================================================================
    #  NHL (32 teams)
    # ========================================================================

    # -- Nickname -> Full --
    (re.compile(r"\bHabs\b", re.IGNORECASE), "Montreal Canadiens"),
    (re.compile(r"\bCanadiens\b", re.IGNORECASE), "Montreal Canadiens"),
    (re.compile(r"\bBolts\b(?!\s+(?:from|and|nut))", re.IGNORECASE), "Tampa Bay Lightning"),
    (re.compile(r"\bCaps\b(?!\s+(?:lock|Lock))", re.IGNORECASE), "Washington Capitals"),
    (re.compile(r"\bCapitals\b", re.IGNORECASE), "Washington Capitals"),
    (re.compile(r"\bPens\b(?!\s+(?:and|ion))", re.IGNORECASE), "Pittsburgh Penguins"),
    (re.compile(r"\bPenguins\b", re.IGNORECASE), "Pittsburgh Penguins"),
    (re.compile(r"\bBruins\b(?!\s+(?:UCLA))", re.IGNORECASE), "Boston Bruins"),
    (re.compile(r"\bLeafs\b", re.IGNORECASE), "Toronto Maple Leafs"),
    (re.compile(r"\bMaple Leafs\b", re.IGNORECASE), "Toronto Maple Leafs"),
    (re.compile(r"\bCanucks\b", re.IGNORECASE), "Vancouver Canucks"),
    (re.compile(r"\bFlames\b", re.IGNORECASE), "Calgary Flames"),
    (re.compile(r"\bOilers\b", re.IGNORECASE), "Edmonton Oilers"),
    (re.compile(r"\bSenators\b(?!\s+(?:vote|bill|US))", re.IGNORECASE), "Ottawa Senators"),
    (re.compile(r"\bSens\b", re.IGNORECASE), "Ottawa Senators"),
    (re.compile(r"\bHurricanes\b(?!\s+(?:category|season))", re.IGNORECASE), "Carolina Hurricanes"),
    (re.compile(r"\bCanes\b", re.IGNORECASE), "Carolina Hurricanes"),
    (re.compile(r"\bAvalanche\b", re.IGNORECASE), "Colorado Avalanche"),
    (re.compile(r"\bAvs\b", re.IGNORECASE), "Colorado Avalanche"),
    (re.compile(r"\bBlackhawks\b", re.IGNORECASE), "Chicago Blackhawks"),
    (re.compile(r"\bBlue Jackets\b", re.IGNORECASE), "Columbus Blue Jackets"),
    (re.compile(r"\bCBJ\b"), "Columbus Blue Jackets"),
    (re.compile(r"\bStars\b(?!\s+(?:Wars|of|in|All))", re.IGNORECASE), "Dallas Stars"),
    (re.compile(r"\bRed Wings\b", re.IGNORECASE), "Detroit Red Wings"),
    (re.compile(r"\bWild\b(?!\s+(?:card|fire|west|life))", re.IGNORECASE), "Minnesota Wild"),
    (re.compile(r"\bPredators\b", re.IGNORECASE), "Nashville Predators"),
    (re.compile(r"\bPreds\b", re.IGNORECASE), "Nashville Predators"),
    (re.compile(r"\bDevils\b", re.IGNORECASE), "New Jersey Devils"),
    (re.compile(r"\bIslanders\b", re.IGNORECASE), "New York Islanders"),
    (re.compile(r"\bIsles\b", re.IGNORECASE), "New York Islanders"),
    (re.compile(r"\bFlyers\b", re.IGNORECASE), "Philadelphia Flyers"),
    (re.compile(r"\bSharks\b", re.IGNORECASE), "San Jose Sharks"),
    (re.compile(r"\bKraken\b", re.IGNORECASE), "Seattle Kraken"),
    (re.compile(r"\bBlues\b(?!\s+(?:music|Brothers|rhythm))", re.IGNORECASE), "St. Louis Blues"),
    (re.compile(r"\bLightning\b(?!\s+(?:bolt|strike|rod))", re.IGNORECASE), "Tampa Bay Lightning"),
    (re.compile(r"\bGolden Knights\b", re.IGNORECASE), "Vegas Golden Knights"),
    (re.compile(r"\bVGK\b"), "Vegas Golden Knights"),
    (re.compile(r"\bDucks\b(?!\s+(?:Oregon|Donald|Mighty))", re.IGNORECASE), "Anaheim Ducks"),
    (re.compile(r"\bSabres\b", re.IGNORECASE), "Buffalo Sabres"),

    # -- Abbreviation -> Full (NHL) --
    (re.compile(r"\bNJD\b"), "New Jersey Devils"),
    (re.compile(r"\bNYI\b"), "New York Islanders"),
    (re.compile(r"\bNYR\b"), "New York Rangers"),
    (re.compile(r"\bTBL\b"), "Tampa Bay Lightning"),
    (re.compile(r"\bWSH\b"), "Washington Capitals"),
    (re.compile(r"\bSJS\b"), "San Jose Sharks"),
    (re.compile(r"\bSTL\b"), "St. Louis Blues"),
    (re.compile(r"\bCGY\b"), "Calgary Flames"),
    (re.compile(r"\bEDM\b"), "Edmonton Oilers"),
    (re.compile(r"\bVAN\b"), "Vancouver Canucks"),
    (re.compile(r"\bWPG\b"), "Winnipeg Jets"),
    (re.compile(r"\bNSH\b"), "Nashville Predators"),
    (re.compile(r"\bOTT\b"), "Ottawa Senators"),
    (re.compile(r"\bMTL\b"), "Montreal Canadiens"),
    (re.compile(r"\bTOR\b"), "Toronto Maple Leafs"),
    (re.compile(r"\bCOL\b(?!\s+(?:orado))", re.IGNORECASE), "Colorado Avalanche"),
    (re.compile(r"\bFLA\b(?!\s+(?:orida))", re.IGNORECASE), "Florida Panthers"),
    (re.compile(r"\bANA\b"), "Anaheim Ducks"),

    # ========================================================================
    #  MLB (30 teams)
    # ========================================================================

    # -- Nickname -> Full --
    (re.compile(r"\bYanks\b", re.IGNORECASE), "New York Yankees"),
    (re.compile(r"\bYankees\b", re.IGNORECASE), "New York Yankees"),
    (re.compile(r"\bBoSox\b", re.IGNORECASE), "Boston Red Sox"),
    (re.compile(r"\bRed Sox\b", re.IGNORECASE), "Boston Red Sox"),
    (re.compile(r"\bWhite Sox\b", re.IGNORECASE), "Chicago White Sox"),
    (re.compile(r"\bChiSox\b", re.IGNORECASE), "Chicago White Sox"),
    (re.compile(r"\bCards\b(?!\s+(?:game|credit|gift))", re.IGNORECASE), "St. Louis Cardinals"),
    (re.compile(r"\bCubbies\b", re.IGNORECASE), "Chicago Cubs"),
    (re.compile(r"\bCubs\b", re.IGNORECASE), "Chicago Cubs"),
    (re.compile(r"\bD-backs\b", re.IGNORECASE), "Arizona Diamondbacks"),
    (re.compile(r"\bDbacks\b", re.IGNORECASE), "Arizona Diamondbacks"),
    (re.compile(r"\bDiamondbacks\b", re.IGNORECASE), "Arizona Diamondbacks"),
    (re.compile(r"\bMets\b", re.IGNORECASE), "New York Mets"),
    (re.compile(r"\bPhillies\b", re.IGNORECASE), "Philadelphia Phillies"),
    (re.compile(r"\bDodgers\b", re.IGNORECASE), "Los Angeles Dodgers"),
    (re.compile(r"\bPadres\b", re.IGNORECASE), "San Diego Padres"),
    (re.compile(r"\bBraves\b", re.IGNORECASE), "Atlanta Braves"),
    (re.compile(r"\bMarlins\b", re.IGNORECASE), "Miami Marlins"),
    (re.compile(r"\bNationals\b(?!\s+(?:Park))", re.IGNORECASE), "Washington Nationals"),
    (re.compile(r"\bNats\b", re.IGNORECASE), "Washington Nationals"),
    (re.compile(r"\bOrioles\b", re.IGNORECASE), "Baltimore Orioles"),
    (re.compile(r"\bO's\b", re.IGNORECASE), "Baltimore Orioles"),
    (re.compile(r"\bBlue Jays\b", re.IGNORECASE), "Toronto Blue Jays"),
    (re.compile(r"\bJays\b(?!\s+(?:Z|Jay|walk))", re.IGNORECASE), "Toronto Blue Jays"),
    (re.compile(r"\bRays\b(?!\s+(?:of|UV))", re.IGNORECASE), "Tampa Bay Rays"),
    (re.compile(r"\bRoyals\b", re.IGNORECASE), "Kansas City Royals"),
    (re.compile(r"\bTwins\b", re.IGNORECASE), "Minnesota Twins"),
    (re.compile(r"\bTigers\b(?!\s+(?:Woods|King|Clemson))", re.IGNORECASE), "Detroit Tigers"),
    (re.compile(r"\bGuardians\b", re.IGNORECASE), "Cleveland Guardians"),
    (re.compile(r"\bBrewers\b", re.IGNORECASE), "Milwaukee Brewers"),
    (re.compile(r"\bReds\b(?!\s+(?:under|Liverpool))", re.IGNORECASE), "Cincinnati Reds"),
    (re.compile(r"\bPirates\b(?!\s+(?:of|Caribbean))", re.IGNORECASE), "Pittsburgh Pirates"),
    (re.compile(r"\bAstros\b", re.IGNORECASE), "Houston Astros"),
    (re.compile(r"\bStros\b", re.IGNORECASE), "Houston Astros"),
    (re.compile(r"\bAngels\b(?!\s+(?:of|in|City|Los))", re.IGNORECASE), "Los Angeles Angels"),
    (re.compile(r"\bHalos\b", re.IGNORECASE), "Los Angeles Angels"),
    (re.compile(r"\bMariners\b", re.IGNORECASE), "Seattle Mariners"),
    (re.compile(r"\bAthletics\b(?!\s+(?:track|field))", re.IGNORECASE), "Oakland Athletics"),
    (re.compile(r"\bA's\b", re.IGNORECASE), "Oakland Athletics"),
    (re.compile(r"\bRockies\b", re.IGNORECASE), "Colorado Rockies"),
    (re.compile(r"\bRangers\b(?!\s+(?:NY|New York|FC|Power|Glasgow))", re.IGNORECASE), "Texas Rangers"),

    # ========================================================================
    #  MLS (29 teams)
    # ========================================================================

    (re.compile(r"\bLAFC\b"), "Los Angeles FC"),
    (re.compile(r"\bNYCFC\b"), "New York City FC"),
    (re.compile(r"\bNYRB\b"), "New York Red Bulls"),
    (re.compile(r"\bRBNY\b"), "New York Red Bulls"),
    (re.compile(r"\bATL UTD\b", re.IGNORECASE), "Atlanta United"),
    (re.compile(r"\bATL United\b", re.IGNORECASE), "Atlanta United"),
    (re.compile(r"\bDC United\b", re.IGNORECASE), "D.C. United"),
    (re.compile(r"\bSKC\b"), "Sporting Kansas City"),
    (re.compile(r"\bSporting KC\b", re.IGNORECASE), "Sporting Kansas City"),
    (re.compile(r"\bMNUFC\b"), "Minnesota United FC"),
    (re.compile(r"\bMinn United\b", re.IGNORECASE), "Minnesota United FC"),
    (re.compile(r"\bCFM\b"), "CF Montreal"),
    (re.compile(r"\bTFC\b"), "Toronto FC"),
    (re.compile(r"\bNERev\b"), "New England Revolution"),
    (re.compile(r"\bRevs\b", re.IGNORECASE), "New England Revolution"),
    (re.compile(r"\bSounders\b", re.IGNORECASE), "Seattle Sounders FC"),
    (re.compile(r"\bTimbers\b", re.IGNORECASE), "Portland Timbers"),
    (re.compile(r"\bWhitecaps\b", re.IGNORECASE), "Vancouver Whitecaps FC"),
    (re.compile(r"\bLA Galaxy\b", re.IGNORECASE), "LA Galaxy"),
    (re.compile(r"\bRSL\b"), "Real Salt Lake"),
    (re.compile(r"\bFCD\b"), "FC Dallas"),
    (re.compile(r"\bFCC\b(?!\s+(?:regulation|commission))", re.IGNORECASE), "FC Cincinnati"),
    (re.compile(r"\bQuakes\b", re.IGNORECASE), "San Jose Earthquakes"),
    (re.compile(r"\bEarthquakes\b", re.IGNORECASE), "San Jose Earthquakes"),
    (re.compile(r"\bDynamo\b(?!\s+(?:Kiev|Kyiv|Moscow|Dresden))", re.IGNORECASE), "Houston Dynamo FC"),
    (re.compile(r"\bInter Miami\b", re.IGNORECASE), "Inter Miami CF"),
    (re.compile(r"\bNashville SC\b", re.IGNORECASE), "Nashville SC"),
    (re.compile(r"\bAustin FC\b", re.IGNORECASE), "Austin FC"),
    (re.compile(r"\bCharlotte FC\b", re.IGNORECASE), "Charlotte FC"),
    (re.compile(r"\bSt\.? Louis City\b", re.IGNORECASE), "St. Louis City SC"),
    (re.compile(r"\bSan Diego FC\b", re.IGNORECASE), "San Diego FC"),
    (re.compile(r"\bColumbus Crew\b", re.IGNORECASE), "Columbus Crew"),
    (re.compile(r"\bChicago Fire\b", re.IGNORECASE), "Chicago Fire FC"),

    # ========================================================================
    #  EPL (20 teams) -- English Premier League
    # ========================================================================

    # -- Existing abbreviations (preserved from original matcher.py) --
    (re.compile(r"\bNottm\b", re.IGNORECASE), "Nottingham"),
    (re.compile(r"\bMan City\b", re.IGNORECASE), "Manchester City"),
    (re.compile(r"\bMan Utd\b", re.IGNORECASE), "Manchester United"),
    (re.compile(r"\bMan United\b", re.IGNORECASE), "Manchester United"),
    (re.compile(r"\bWolves\b", re.IGNORECASE), "Wolverhampton Wanderers"),
    (re.compile(r"\bSheff\b", re.IGNORECASE), "Sheffield"),
    (re.compile(r"\bSoton\b", re.IGNORECASE), "Southampton"),
    (re.compile(r"\bBham\b", re.IGNORECASE), "Birmingham"),
    (re.compile(r"\bSpurs\b", re.IGNORECASE), "Tottenham Hotspur"),
    (re.compile(r"\bGunners\b", re.IGNORECASE), "Arsenal"),
    (re.compile(r"\bNUFC\b"), "Newcastle United"),
    (re.compile(r"\bAVFC\b"), "Aston Villa"),
    (re.compile(r"\bWHU\b"), "West Ham United"),

    # -- Nicknames -> Full --
    (re.compile(r"\bToffees\b", re.IGNORECASE), "Everton"),
    (re.compile(r"\bHammers\b", re.IGNORECASE), "West Ham United"),
    (re.compile(r"\bVillans\b", re.IGNORECASE), "Aston Villa"),
    (re.compile(r"\bMagpies\b", re.IGNORECASE), "Newcastle United"),
    (re.compile(r"\bCherries\b", re.IGNORECASE), "AFC Bournemouth"),
    (re.compile(r"\bBlades\b", re.IGNORECASE), "Sheffield United"),
    (re.compile(r"\bFoxes\b", re.IGNORECASE), "Leicester City"),
    (re.compile(r"\bBees\b(?!\s+(?:wax|honey|spelling))", re.IGNORECASE), "Brentford"),
    (re.compile(r"\bCanaries\b", re.IGNORECASE), "Norwich City"),
    (re.compile(r"\bSeagulls\b", re.IGNORECASE), "Brighton and Hove Albion"),
    (re.compile(r"\bBrighton\b", re.IGNORECASE), "Brighton and Hove Albion"),
    (re.compile(r"\bBaggies\b", re.IGNORECASE), "West Bromwich Albion"),
    (re.compile(r"\bWBA\b"), "West Bromwich Albion"),

    # -- Club abbreviations --
    (re.compile(r"\bLFC\b"), "Liverpool"),
    (re.compile(r"\bCFC\b(?!\s+(?:Montreal))", re.IGNORECASE), "Chelsea"),
    (re.compile(r"\bMCFC\b"), "Manchester City"),
    (re.compile(r"\bMUFC\b"), "Manchester United"),
    (re.compile(r"\bTHFC\b"), "Tottenham Hotspur"),
    (re.compile(r"\bWWFC\b"), "Wolverhampton Wanderers"),
    (re.compile(r"\bNFFC\b"), "Nottingham Forest"),

    # -- Full name normalization --
    (re.compile(r"\bBournemouth\b", re.IGNORECASE), "AFC Bournemouth"),
    (re.compile(r"\bLeicester\b", re.IGNORECASE), "Leicester City"),
    (re.compile(r"\bIpswich\b", re.IGNORECASE), "Ipswich Town"),
    (re.compile(r"\bNewcastle\b(?!\s+(?:upon|disease))", re.IGNORECASE), "Newcastle United"),
    (re.compile(r"\bWest Ham\b", re.IGNORECASE), "West Ham United"),
    (re.compile(r"\bWolverhampton\b", re.IGNORECASE), "Wolverhampton Wanderers"),
    (re.compile(r"\bTottenham\b", re.IGNORECASE), "Tottenham Hotspur"),
    (re.compile(r"\bCrystal Palace\b", re.IGNORECASE), "Crystal Palace"),
    (re.compile(r"\bAston Villa\b", re.IGNORECASE), "Aston Villa"),
    (re.compile(r"\bNottingham Forest\b", re.IGNORECASE), "Nottingham Forest"),
    (re.compile(r"\bPhilly\b", re.IGNORECASE), "Philadelphia"),

    # ========================================================================
    #  La Liga (20 teams)
    # ========================================================================

    (re.compile(r"\bBarca\b", re.IGNORECASE), "FC Barcelona"),
    (re.compile(r"\bBarcelona\b(?!\s+(?:city|Spain))", re.IGNORECASE), "FC Barcelona"),
    (re.compile(r"\bReal Madrid\b", re.IGNORECASE), "Real Madrid"),
    (re.compile(r"\bAtl\.?\s*Madrid\b", re.IGNORECASE), "Atletico Madrid"),
    (re.compile(r"\bAtleti\b", re.IGNORECASE), "Atletico Madrid"),
    (re.compile(r"\bAtletico\b(?!\s+(?:Nacional|Mineiro|Paranaense))", re.IGNORECASE), "Atletico Madrid"),
    (re.compile(r"\bSevilla\b(?!\s+(?:city))", re.IGNORECASE), "Sevilla FC"),
    (re.compile(r"\bBetis\b", re.IGNORECASE), "Real Betis"),
    (re.compile(r"\bReal Sociedad\b", re.IGNORECASE), "Real Sociedad"),
    (re.compile(r"\bLa Real\b", re.IGNORECASE), "Real Sociedad"),
    (re.compile(r"\bVillarreal\b", re.IGNORECASE), "Villarreal CF"),
    (re.compile(r"\bYellow Submarine\b", re.IGNORECASE), "Villarreal CF"),
    (re.compile(r"\bAthletic Bilbao\b", re.IGNORECASE), "Athletic Club"),
    (re.compile(r"\bAthletic Club\b", re.IGNORECASE), "Athletic Club"),
    (re.compile(r"\bValencia\b(?!\s+(?:city|Spain|Community))", re.IGNORECASE), "Valencia CF"),
    (re.compile(r"\bOsasuna\b", re.IGNORECASE), "CA Osasuna"),
    (re.compile(r"\bCelta\b", re.IGNORECASE), "Celta Vigo"),
    (re.compile(r"\bCelta Vigo\b", re.IGNORECASE), "RC Celta de Vigo"),
    (re.compile(r"\bGetafe\b", re.IGNORECASE), "Getafe CF"),
    (re.compile(r"\bMallorca\b", re.IGNORECASE), "RCD Mallorca"),
    (re.compile(r"\bGirona\b", re.IGNORECASE), "Girona FC"),
    (re.compile(r"\bLas Palmas\b", re.IGNORECASE), "UD Las Palmas"),
    (re.compile(r"\bCadiz\b", re.IGNORECASE), "Cadiz CF"),
    (re.compile(r"\bAlaves\b", re.IGNORECASE), "Deportivo Alaves"),
    (re.compile(r"\bAlmeria\b", re.IGNORECASE), "UD Almeria"),
    (re.compile(r"\bRayo\b(?!\s+(?:de|del))", re.IGNORECASE), "Rayo Vallecano"),
    (re.compile(r"\bEspanyol\b", re.IGNORECASE), "RCD Espanyol"),
    (re.compile(r"\bReal Valladolid\b", re.IGNORECASE), "Real Valladolid"),
    (re.compile(r"\bLeganes\b", re.IGNORECASE), "CD Leganes"),

    # ========================================================================
    #  Bundesliga (18 teams)
    # ========================================================================

    (re.compile(r"\bBayern\b", re.IGNORECASE), "Bayern Munich"),
    (re.compile(r"\bBayern Munich\b", re.IGNORECASE), "FC Bayern Munich"),
    (re.compile(r"\bBayern Munchen\b", re.IGNORECASE), "FC Bayern Munich"),
    (re.compile(r"\bFCB\b(?!\s+(?:arcelona))", re.IGNORECASE), "FC Bayern Munich"),
    (re.compile(r"\bDortmund\b", re.IGNORECASE), "Borussia Dortmund"),
    (re.compile(r"\bBVB\b"), "Borussia Dortmund"),
    (re.compile(r"\bLeverkusen\b", re.IGNORECASE), "Bayer Leverkusen"),
    (re.compile(r"\bGladbach\b", re.IGNORECASE), "Borussia Monchengladbach"),
    (re.compile(r"\bBMG\b"), "Borussia Monchengladbach"),
    (re.compile(r"\bRB Leipzig\b", re.IGNORECASE), "RB Leipzig"),
    (re.compile(r"\bLeipzig\b(?!\s+(?:Battle|debate))", re.IGNORECASE), "RB Leipzig"),
    (re.compile(r"\bWolfsburg\b", re.IGNORECASE), "VfL Wolfsburg"),
    (re.compile(r"\bFreiburg\b", re.IGNORECASE), "SC Freiburg"),
    (re.compile(r"\bFrankfurt\b(?!\s+(?:School|Book|am))", re.IGNORECASE), "Eintracht Frankfurt"),
    (re.compile(r"\bEintracht\b(?!\s+(?:Frankfurt))", re.IGNORECASE), "Eintracht Frankfurt"),
    (re.compile(r"\bSGE\b"), "Eintracht Frankfurt"),
    (re.compile(r"\bStuttgart\b", re.IGNORECASE), "VfB Stuttgart"),
    (re.compile(r"\bUnion Berlin\b", re.IGNORECASE), "1. FC Union Berlin"),
    (re.compile(r"\bHertha\b", re.IGNORECASE), "Hertha BSC"),
    (re.compile(r"\bAugsburg\b", re.IGNORECASE), "FC Augsburg"),
    (re.compile(r"\bMainz\b", re.IGNORECASE), "1. FSV Mainz 05"),
    (re.compile(r"\bHoffenheim\b", re.IGNORECASE), "TSG Hoffenheim"),
    (re.compile(r"\bTSG\b"), "TSG Hoffenheim"),
    (re.compile(r"\bBochum\b", re.IGNORECASE), "VfL Bochum"),
    (re.compile(r"\bKoln\b", re.IGNORECASE), "1. FC Koln"),
    (re.compile(r"\bCologne\b(?!\s+(?:Germany|city))", re.IGNORECASE), "1. FC Koln"),
    (re.compile(r"\bWerder\b", re.IGNORECASE), "Werder Bremen"),
    (re.compile(r"\bBremen\b", re.IGNORECASE), "Werder Bremen"),
    (re.compile(r"\bDarmstadt\b", re.IGNORECASE), "SV Darmstadt 98"),
    (re.compile(r"\bHeidenheim\b", re.IGNORECASE), "1. FC Heidenheim"),
    (re.compile(r"\bSt\.? Pauli\b", re.IGNORECASE), "FC St. Pauli"),
    (re.compile(r"\bHolstein Kiel\b", re.IGNORECASE), "Holstein Kiel"),

    # ========================================================================
    #  Serie A (20 teams)
    # ========================================================================

    (re.compile(r"\bInter\b(?!\s+(?:Miami|national|net|ior|view))", re.IGNORECASE), "Inter Milan"),
    (re.compile(r"\bInter Milan\b", re.IGNORECASE), "FC Internazionale Milano"),
    (re.compile(r"\bJuve\b", re.IGNORECASE), "Juventus"),
    (re.compile(r"\bJuventus\b", re.IGNORECASE), "Juventus FC"),
    (re.compile(r"\bRoma\b(?!\s+(?:n\b|nce|ntic|nian))", re.IGNORECASE), "AS Roma"),
    (re.compile(r"\bNapoli\b", re.IGNORECASE), "SSC Napoli"),
    (re.compile(r"\bAC Milan\b", re.IGNORECASE), "AC Milan"),
    (re.compile(r"\bMilan\b(?!\s+(?:Kundera|AC|Inter|city))", re.IGNORECASE), "AC Milan"),
    (re.compile(r"\bLazio\b", re.IGNORECASE), "SS Lazio"),
    (re.compile(r"\bFiorentina\b", re.IGNORECASE), "ACF Fiorentina"),
    (re.compile(r"\bViola\b(?!\s+(?:Davis|color))", re.IGNORECASE), "ACF Fiorentina"),
    (re.compile(r"\bAtalanta\b(?!\s+(?:Georgia|Hawks|Falcons|United|Braves))", re.IGNORECASE), "Atalanta BC"),
    (re.compile(r"\bBologna\b(?!\s+(?:Italy|city|process))", re.IGNORECASE), "Bologna FC"),
    (re.compile(r"\bTorino\b", re.IGNORECASE), "Torino FC"),
    (re.compile(r"\bSassuolo\b", re.IGNORECASE), "US Sassuolo"),
    (re.compile(r"\bEmpoli\b", re.IGNORECASE), "Empoli FC"),
    (re.compile(r"\bGenoa\b", re.IGNORECASE), "Genoa CFC"),
    (re.compile(r"\bSampdoria\b", re.IGNORECASE), "UC Sampdoria"),
    (re.compile(r"\bUdinese\b", re.IGNORECASE), "Udinese Calcio"),
    (re.compile(r"\bMonza\b(?!\s+(?:Grand Prix|GP|race))", re.IGNORECASE), "AC Monza"),
    (re.compile(r"\bSalernitana\b", re.IGNORECASE), "US Salernitana"),
    (re.compile(r"\bCagliari\b", re.IGNORECASE), "Cagliari Calcio"),
    (re.compile(r"\bLecce\b", re.IGNORECASE), "US Lecce"),
    (re.compile(r"\bFrosinone\b", re.IGNORECASE), "Frosinone Calcio"),
    (re.compile(r"\bHellas Verona\b", re.IGNORECASE), "Hellas Verona FC"),
    (re.compile(r"\bVerona\b(?!\s+(?:Hellas|Italy|city))", re.IGNORECASE), "Hellas Verona FC"),
    (re.compile(r"\bVenezia\b", re.IGNORECASE), "Venezia FC"),
    (re.compile(r"\bParma\b(?!\s+(?:ham|Italy|city))", re.IGNORECASE), "Parma Calcio"),
    (re.compile(r"\bComo\b(?!\s+(?:Lake|Italy))", re.IGNORECASE), "Como 1907"),

    # ========================================================================
    #  Ligue 1 (18 teams)
    # ========================================================================

    (re.compile(r"\bPSG\b"), "Paris Saint-Germain"),
    (re.compile(r"\bParis SG\b", re.IGNORECASE), "Paris Saint-Germain"),
    (re.compile(r"\bParis Saint Germain\b", re.IGNORECASE), "Paris Saint-Germain"),
    (re.compile(r"\bMarseille\b", re.IGNORECASE), "Olympique de Marseille"),
    (re.compile(r"\bOM\b(?!\s+(?:G|my))", re.IGNORECASE), "Olympique de Marseille"),
    (re.compile(r"\bLyon\b(?!\s+(?:France|city))", re.IGNORECASE), "Olympique Lyonnais"),
    (re.compile(r"\bOL\b(?!\s+(?:d\b))", re.IGNORECASE), "Olympique Lyonnais"),
    (re.compile(r"\bMonaco\b(?!\s+(?:Grand Prix|GP|Prince))", re.IGNORECASE), "AS Monaco"),
    (re.compile(r"\bLille\b", re.IGNORECASE), "LOSC Lille"),
    (re.compile(r"\bLOSC\b"), "LOSC Lille"),
    (re.compile(r"\bRennes\b", re.IGNORECASE), "Stade Rennais"),
    (re.compile(r"\bNice\b(?!\s+(?:try|job|day|to|one|work|thing))", re.IGNORECASE), "OGC Nice"),
    (re.compile(r"\bLens\b(?!\s+(?:cap|es\b|focal))", re.IGNORECASE), "RC Lens"),
    (re.compile(r"\bStrasbourg\b", re.IGNORECASE), "RC Strasbourg"),
    (re.compile(r"\bNantes\b", re.IGNORECASE), "FC Nantes"),
    (re.compile(r"\bToulouse\b", re.IGNORECASE), "Toulouse FC"),
    (re.compile(r"\bMontpellier\b", re.IGNORECASE), "Montpellier HSC"),
    (re.compile(r"\bReims\b", re.IGNORECASE), "Stade de Reims"),
    (re.compile(r"\bBrest\b(?!\s+(?:cancer|feeding))", re.IGNORECASE), "Stade Brestois"),
    (re.compile(r"\bClermont\b", re.IGNORECASE), "Clermont Foot"),
    (re.compile(r"\bLorient\b", re.IGNORECASE), "FC Lorient"),
    (re.compile(r"\bMetz\b", re.IGNORECASE), "FC Metz"),
    (re.compile(r"\bLe Havre\b", re.IGNORECASE), "Le Havre AC"),
    (re.compile(r"\bAngers\b", re.IGNORECASE), "Angers SCO"),
    (re.compile(r"\bAuxerre\b", re.IGNORECASE), "AJ Auxerre"),
    (re.compile(r"\bSaint-Etienne\b", re.IGNORECASE), "AS Saint-Etienne"),
    (re.compile(r"\bSt Etienne\b", re.IGNORECASE), "AS Saint-Etienne"),

    # ========================================================================
    #  NCAA -- Top ~40 programs (basketball + football)
    #  Skipping ambiguous mascots: Wildcats, Tigers, Bulldogs, Bears, Eagles
    # ========================================================================

    (re.compile(r"\bBama\b", re.IGNORECASE), "Alabama Crimson Tide"),
    (re.compile(r"\bCrimson Tide\b", re.IGNORECASE), "Alabama Crimson Tide"),
    (re.compile(r"\bRoll Tide\b", re.IGNORECASE), "Alabama Crimson Tide"),
    (re.compile(r"\bBuckeyes\b", re.IGNORECASE), "Ohio State Buckeyes"),
    (re.compile(r"\bSooners\b", re.IGNORECASE), "Oklahoma Sooners"),
    (re.compile(r"\bLonghorns\b", re.IGNORECASE), "Texas Longhorns"),
    (re.compile(r"\bHook Em\b", re.IGNORECASE), "Texas Longhorns"),
    (re.compile(r"\bWolverines\b", re.IGNORECASE), "Michigan Wolverines"),
    (re.compile(r"\bSpartans\b", re.IGNORECASE), "Michigan State Spartans"),
    (re.compile(r"\bNittany Lions\b", re.IGNORECASE), "Penn State Nittany Lions"),
    (re.compile(r"\bPenn State\b", re.IGNORECASE), "Penn State Nittany Lions"),
    (re.compile(r"\bFighting Irish\b", re.IGNORECASE), "Notre Dame Fighting Irish"),
    (re.compile(r"\bNotre Dame\b(?!\s+(?:Cathedral|Paris))", re.IGNORECASE), "Notre Dame Fighting Irish"),
    (re.compile(r"\bTar Heels\b", re.IGNORECASE), "North Carolina Tar Heels"),
    (re.compile(r"\bUNC\b"), "North Carolina Tar Heels"),
    (re.compile(r"\bBlue Devils\b", re.IGNORECASE), "Duke Blue Devils"),
    (re.compile(r"\bJayhawks\b", re.IGNORECASE), "Kansas Jayhawks"),
    (re.compile(r"\bHoosiers\b", re.IGNORECASE), "Indiana Hoosiers"),
    (re.compile(r"\bBoilermakers\b", re.IGNORECASE), "Purdue Boilermakers"),
    (re.compile(r"\bCornhuskers\b", re.IGNORECASE), "Nebraska Cornhuskers"),
    (re.compile(r"\bHuskers\b", re.IGNORECASE), "Nebraska Cornhuskers"),
    (re.compile(r"\bHawkeyes\b", re.IGNORECASE), "Iowa Hawkeyes"),
    (re.compile(r"\bGators\b", re.IGNORECASE), "Florida Gators"),
    (re.compile(r"\bVolunteers\b", re.IGNORECASE), "Tennessee Volunteers"),
    (re.compile(r"\bVols\b", re.IGNORECASE), "Tennessee Volunteers"),
    (re.compile(r"\bGamecocks\b", re.IGNORECASE), "South Carolina Gamecocks"),
    (re.compile(r"\bRazorbacks\b", re.IGNORECASE), "Arkansas Razorbacks"),
    (re.compile(r"\bAggies\b", re.IGNORECASE), "Texas A&M Aggies"),
    (re.compile(r"\bSeminoles\b", re.IGNORECASE), "Florida State Seminoles"),
    (re.compile(r"\bFSU\b"), "Florida State Seminoles"),
    (re.compile(r"\bNoles\b", re.IGNORECASE), "Florida State Seminoles"),
    (re.compile(r"\bTerrapins\b", re.IGNORECASE), "Maryland Terrapins"),
    (re.compile(r"\bTerps\b", re.IGNORECASE), "Maryland Terrapins"),
    (re.compile(r"\bUConn\b", re.IGNORECASE), "Connecticut Huskies"),
    (re.compile(r"\bZags\b", re.IGNORECASE), "Gonzaga Bulldogs"),
    (re.compile(r"\bGonzaga\b", re.IGNORECASE), "Gonzaga Bulldogs"),
    (re.compile(r"\bSun Devils\b", re.IGNORECASE), "Arizona State Sun Devils"),
    (re.compile(r"\bASU\b"), "Arizona State Sun Devils"),
    (re.compile(r"\bCommodores\b", re.IGNORECASE), "Vanderbilt Commodores"),
    (re.compile(r"\bVanderbilt\b", re.IGNORECASE), "Vanderbilt Commodores"),
    (re.compile(r"\bBeavers\b", re.IGNORECASE), "Oregon State Beavers"),
    (re.compile(r"\bCyclones\b", re.IGNORECASE), "Iowa State Cyclones"),
    (re.compile(r"\bRed Raiders\b", re.IGNORECASE), "Texas Tech Red Raiders"),
    (re.compile(r"\bHorned Frogs\b", re.IGNORECASE), "TCU Horned Frogs"),
    (re.compile(r"\bTCU\b"), "TCU Horned Frogs"),
    (re.compile(r"\bMountaineers\b", re.IGNORECASE), "West Virginia Mountaineers"),
    (re.compile(r"\bUCLA\b"), "UCLA Bruins"),
    (re.compile(r"\bUSC Trojans\b", re.IGNORECASE), "USC Trojans"),
    (re.compile(r"\bTrojans\b(?!\s+(?:horse|war))", re.IGNORECASE), "USC Trojans"),
    (re.compile(r"\bOregon Ducks\b", re.IGNORECASE), "Oregon Ducks"),
    (re.compile(r"\bClemson\b", re.IGNORECASE), "Clemson Tigers"),
    (re.compile(r"\bCrimson\b(?!\s+(?:Tide))", re.IGNORECASE), "Harvard Crimson"),

    # ========================================================================
    #  Other Soccer (UCL, Europa, Scottish Prem, Brazilian, etc.)
    # ========================================================================

    # -- UCL regulars not covered above --
    (re.compile(r"\bFC Porto\b", re.IGNORECASE), "Porto"),
    (re.compile(r"\bBenfica\b", re.IGNORECASE), "SL Benfica"),
    (re.compile(r"\bSporting CP\b", re.IGNORECASE), "Sporting CP"),
    (re.compile(r"\bSporting Lisbon\b", re.IGNORECASE), "Sporting CP"),
    (re.compile(r"\bAjax\b", re.IGNORECASE), "AFC Ajax"),
    (re.compile(r"\bFeyenoord\b", re.IGNORECASE), "Feyenoord Rotterdam"),
    (re.compile(r"\bPSV\b"), "PSV Eindhoven"),
    (re.compile(r"\bGalatasaray\b", re.IGNORECASE), "Galatasaray SK"),
    (re.compile(r"\bFenerbahce\b", re.IGNORECASE), "Fenerbahce SK"),
    (re.compile(r"\bBesiktas\b", re.IGNORECASE), "Besiktas JK"),
    (re.compile(r"\bCeltic\b(?!\s+(?:FC|s\b))", re.IGNORECASE), "Celtic FC"),
    (re.compile(r"\bRangers FC\b", re.IGNORECASE), "Rangers FC"),
    (re.compile(r"\bShakhtar\b", re.IGNORECASE), "Shakhtar Donetsk"),
    (re.compile(r"\bDynamo Kyiv\b", re.IGNORECASE), "Dynamo Kyiv"),
    (re.compile(r"\bDynamo Kiev\b", re.IGNORECASE), "Dynamo Kyiv"),
    (re.compile(r"\bRed Star Belgrade\b", re.IGNORECASE), "Red Star Belgrade"),
    (re.compile(r"\bSalzburg\b", re.IGNORECASE), "RB Salzburg"),
    (re.compile(r"\bClub Brugge\b", re.IGNORECASE), "Club Brugge KV"),
    (re.compile(r"\bYoung Boys\b", re.IGNORECASE), "BSC Young Boys"),

    # -- Scottish Premiership --
    (re.compile(r"\bAberdeen\b(?!\s+(?:Proving|city))", re.IGNORECASE), "Aberdeen FC"),
    (re.compile(r"\bHibs\b", re.IGNORECASE), "Hibernian"),
    (re.compile(r"\bHearts\b(?!\s+(?:of|card))", re.IGNORECASE), "Heart of Midlothian"),
    (re.compile(r"\bDundee United\b", re.IGNORECASE), "Dundee United"),
    (re.compile(r"\bSt Mirren\b", re.IGNORECASE), "St Mirren"),
    (re.compile(r"\bMotherwell\b", re.IGNORECASE), "Motherwell FC"),
    (re.compile(r"\bKilmarnock\b", re.IGNORECASE), "Kilmarnock FC"),

    # -- Brazilian Serie A (top teams) --
    (re.compile(r"\bFlamengo\b", re.IGNORECASE), "CR Flamengo"),
    (re.compile(r"\bMengo\b", re.IGNORECASE), "CR Flamengo"),
    (re.compile(r"\bPalmeiras\b", re.IGNORECASE), "SE Palmeiras"),
    (re.compile(r"\bCorinthians\b", re.IGNORECASE), "SC Corinthians"),
    (re.compile(r"\bSantos\b(?!\s+FC)", re.IGNORECASE), "Santos FC"),
    (re.compile(r"\bGremio\b", re.IGNORECASE), "Gremio FBPA"),
    (re.compile(r"\bInternacional\b", re.IGNORECASE), "SC Internacional"),
    (re.compile(r"\bAtletico Mineiro\b", re.IGNORECASE), "Atletico Mineiro"),
    (re.compile(r"\bGalo\b", re.IGNORECASE), "Atletico Mineiro"),
    (re.compile(r"\bFluminense\b", re.IGNORECASE), "Fluminense FC"),
    (re.compile(r"\bBotafogo\b", re.IGNORECASE), "Botafogo FR"),

    # ========================================================================
    #  Tennis (common name abbreviations)
    # ========================================================================

    (re.compile(r"\bNole\b", re.IGNORECASE), "Novak Djokovic"),
    (re.compile(r"\bDjokovic\b", re.IGNORECASE), "Novak Djokovic"),
    (re.compile(r"\bNadal\b", re.IGNORECASE), "Rafael Nadal"),
    (re.compile(r"\bRafa\b", re.IGNORECASE), "Rafael Nadal"),
    (re.compile(r"\bFederer\b", re.IGNORECASE), "Roger Federer"),
    (re.compile(r"\bAlcaraz\b", re.IGNORECASE), "Carlos Alcaraz"),
    (re.compile(r"\bSinner\b(?!\s+(?:or|and))", re.IGNORECASE), "Jannik Sinner"),
    (re.compile(r"\bMedvedev\b(?!\s+(?:Dmitry|Russian|President))", re.IGNORECASE), "Daniil Medvedev"),
    (re.compile(r"\bSwiatek\b", re.IGNORECASE), "Iga Swiatek"),
    (re.compile(r"\bSabalenka\b", re.IGNORECASE), "Aryna Sabalenka"),
    (re.compile(r"\bGauff\b", re.IGNORECASE), "Coco Gauff"),

    # ========================================================================
    #  Crypto -- Token names & dollar amounts
    # ========================================================================

    # -- Token names --
    (re.compile(r"\bBTC\b"), "Bitcoin"),
    (re.compile(r"\bETH\b"), "Ethereum"),
    (re.compile(r"\bSOL\b(?!\s+(?:ution|ve|ar|id|omon))", re.IGNORECASE), "Solana"),
    (re.compile(r"\bXRP\b"), "Ripple"),
    (re.compile(r"\bDOGE\b"), "Dogecoin"),
    (re.compile(r"\bADA\b(?!\s+(?:compliance|Act|Lovelace))", re.IGNORECASE), "Cardano"),
    (re.compile(r"\bDOT\b(?!\s+(?:com))", re.IGNORECASE), "Polkadot"),
    (re.compile(r"\bAVAX\b"), "Avalanche"),
    (re.compile(r"\bMATIC\b"), "Polygon"),
    (re.compile(r"\bLINK\b(?!\s+(?:ed|s\b|tree))", re.IGNORECASE), "Chainlink"),
    (re.compile(r"\bUNI\b(?!\s+(?:versity|form|on|ted|que))", re.IGNORECASE), "Uniswap"),
    (re.compile(r"\bLTC\b"), "Litecoin"),
    (re.compile(r"\bBNB\b"), "Binance Coin"),
    (re.compile(r"\bATOM\b(?!\s+(?:ic))", re.IGNORECASE), "Cosmos"),
    (re.compile(r"\bSHIB\b"), "Shiba Inu"),
    (re.compile(r"\bAPT\b"), "Aptos"),
    (re.compile(r"\bSUI\b"), "Sui"),
    (re.compile(r"\bARB\b(?!\s+(?:itration|itrary))", re.IGNORECASE), "Arbitrum"),
    (re.compile(r"\bNEAR\b(?!\s+(?:by|ly|er|est))", re.IGNORECASE), "NEAR Protocol"),
    (re.compile(r"\bFIL\b(?!\s+(?:e|m|ter|ing))", re.IGNORECASE), "Filecoin"),

    # -- Dollar amounts (k = thousands) --
    (re.compile(r"\$10k\b", re.IGNORECASE), "$10000"),
    (re.compile(r"\$15k\b", re.IGNORECASE), "$15000"),
    (re.compile(r"\$20k\b", re.IGNORECASE), "$20000"),
    (re.compile(r"\$25k\b", re.IGNORECASE), "$25000"),
    (re.compile(r"\$30k\b", re.IGNORECASE), "$30000"),
    (re.compile(r"\$40k\b", re.IGNORECASE), "$40000"),
    (re.compile(r"\$50k\b", re.IGNORECASE), "$50000"),
    (re.compile(r"\$60k\b", re.IGNORECASE), "$60000"),
    (re.compile(r"\$75k\b", re.IGNORECASE), "$75000"),
    (re.compile(r"\$80k\b", re.IGNORECASE), "$80000"),
    (re.compile(r"\$90k\b", re.IGNORECASE), "$90000"),
    (re.compile(r"\$100k\b", re.IGNORECASE), "$100000"),
    (re.compile(r"\$110k\b", re.IGNORECASE), "$110000"),
    (re.compile(r"\$120k\b", re.IGNORECASE), "$120000"),
    (re.compile(r"\$125k\b", re.IGNORECASE), "$125000"),
    (re.compile(r"\$130k\b", re.IGNORECASE), "$130000"),
    (re.compile(r"\$140k\b", re.IGNORECASE), "$140000"),
    (re.compile(r"\$150k\b", re.IGNORECASE), "$150000"),
    (re.compile(r"\$175k\b", re.IGNORECASE), "$175000"),
    (re.compile(r"\$200k\b", re.IGNORECASE), "$200000"),
    (re.compile(r"\$250k\b", re.IGNORECASE), "$250000"),
    (re.compile(r"\$300k\b", re.IGNORECASE), "$300000"),
    (re.compile(r"\$350k\b", re.IGNORECASE), "$350000"),
    (re.compile(r"\$400k\b", re.IGNORECASE), "$400000"),
    (re.compile(r"\$500k\b", re.IGNORECASE), "$500000"),
    (re.compile(r"\$750k\b", re.IGNORECASE), "$750000"),

    # -- Dollar amounts (M = millions) --
    (re.compile(r"\$1M\b", re.IGNORECASE), "$1000000"),
    (re.compile(r"\$1\.5M\b", re.IGNORECASE), "$1500000"),
    (re.compile(r"\$2M\b", re.IGNORECASE), "$2000000"),
    (re.compile(r"\$2\.5M\b", re.IGNORECASE), "$2500000"),
    (re.compile(r"\$3M\b", re.IGNORECASE), "$3000000"),
    (re.compile(r"\$5M\b", re.IGNORECASE), "$5000000"),
    (re.compile(r"\$10M\b", re.IGNORECASE), "$10000000"),
    (re.compile(r"\$50M\b", re.IGNORECASE), "$50000000"),
    (re.compile(r"\$100M\b", re.IGNORECASE), "$100000000"),

    # -- Kalshi dollar-formatted amounts with commas --
    (re.compile(r"\$149,999\.99\b"), "$150000"),
    (re.compile(r"\$109,999\.99\b"), "$110000"),
    (re.compile(r"\$99,999\.99\b"), "$100000"),
    (re.compile(r"\$124,999\.99\b"), "$125000"),
    (re.compile(r"\$129,999\.99\b"), "$130000"),
    (re.compile(r"\$139,999\.99\b"), "$140000"),
    (re.compile(r"\$199,999\.99\b"), "$200000"),
    (re.compile(r"\$249,999\.99\b"), "$250000"),
    (re.compile(r"\$299,999\.99\b"), "$300000"),
    (re.compile(r"\$499,999\.99\b"), "$500000"),
    (re.compile(r"\$999,999\.99\b"), "$1000000"),

    # ========================================================================
    #  Politics
    # ========================================================================

    (re.compile(r"\bPOTUS\b"), "President"),
    (re.compile(r"\bSCOTUS\b"), "Supreme Court"),
    (re.compile(r"\bGOP\b"), "Republican"),
    (re.compile(r"\bDems\b", re.IGNORECASE), "Democrats"),
    (re.compile(r"\bDem\b(?!\s+(?:olition|ocra))", re.IGNORECASE), "Democrat"),
    (re.compile(r"\bRepubs\b", re.IGNORECASE), "Republicans"),
    (re.compile(r"\bRepub\b(?!\s+(?:lic))", re.IGNORECASE), "Republican"),
    (re.compile(r"\bRFK\b"), "Robert F. Kennedy"),
    (re.compile(r"\bRFK Jr\.?\b", re.IGNORECASE), "Robert F. Kennedy Jr."),
    (re.compile(r"\bDJT\b"), "Donald Trump"),
    (re.compile(r"\bAOC\b"), "Alexandria Ocasio-Cortez"),
    (re.compile(r"\bMTG\b(?!\s+(?:Arena|card))", re.IGNORECASE), "Marjorie Taylor Greene"),
    (re.compile(r"\bDeSantis\b", re.IGNORECASE), "Ron DeSantis"),
    (re.compile(r"\bNewsom\b", re.IGNORECASE), "Gavin Newsom"),
    (re.compile(r"\bVP\b(?!\s+(?:of|at))", re.IGNORECASE), "Vice President"),
    (re.compile(r"\bSen\.\s", re.IGNORECASE), "Senator "),
    (re.compile(r"\bRep\.\s", re.IGNORECASE), "Representative "),
    (re.compile(r"\bGov\.\s", re.IGNORECASE), "Governor "),
    (re.compile(r"\bFed Chair\b", re.IGNORECASE), "Federal Reserve Chair"),
    (re.compile(r"\bFed\b(?!\s+(?:Chair|Reserve|eral|Ex|Cup))", re.IGNORECASE), "Federal Reserve"),
    (re.compile(r"\bEPA\b"), "Environmental Protection Agency"),
    (re.compile(r"\bDOJ\b"), "Department of Justice"),
    (re.compile(r"\bDOD\b"), "Department of Defense"),
    (re.compile(r"\bCIA\b"), "Central Intelligence Agency"),
    (re.compile(r"\bFBI\b"), "Federal Bureau of Investigation"),
    (re.compile(r"\bSEC\b(?!\s+(?:ond|tion|ret))", re.IGNORECASE), "Securities and Exchange Commission"),
    (re.compile(r"\bFTC\b"), "Federal Trade Commission"),
    (re.compile(r"\bCDC\b"), "Centers for Disease Control"),
    (re.compile(r"\bFDA\b"), "Food and Drug Administration"),

    # ========================================================================
    #  Entertainment / Awards
    # ========================================================================

    (re.compile(r"\bAcademy Awards?\b", re.IGNORECASE), "Oscars"),
    (re.compile(r"\b98th Oscars\b", re.IGNORECASE), "Oscars"),
    (re.compile(r"\bGrammys\b", re.IGNORECASE), "Grammy Awards"),
    (re.compile(r"\bGrammy\b(?!\s+(?:Awards?))", re.IGNORECASE), "Grammy Awards"),
    (re.compile(r"\bEmmys\b", re.IGNORECASE), "Emmy Awards"),
    (re.compile(r"\bEmmy\b(?!\s+(?:Awards?))", re.IGNORECASE), "Emmy Awards"),
    (re.compile(r"\bGolden Globes?\b", re.IGNORECASE), "Golden Globe Awards"),
    (re.compile(r"\bTonys\b(?!\s+(?:Hawk|Montana|Stark|Blair|Parker|Soprano|Stewart))", re.IGNORECASE), "Tony Awards"),
    (re.compile(r"\bTony Awards?\b", re.IGNORECASE), "Tony Awards"),
    (re.compile(r"\bBAFTAs?\b", re.IGNORECASE), "BAFTA Awards"),
    (re.compile(r"\bSAG Awards?\b", re.IGNORECASE), "Screen Actors Guild Awards"),
    (re.compile(r"\bSAG-AFTRA\b"), "Screen Actors Guild Awards"),
    (re.compile(r"\bCritics Choice\b", re.IGNORECASE), "Critics Choice Awards"),
    (re.compile(r"\bPeople'?s Choice\b", re.IGNORECASE), "People's Choice Awards"),
    (re.compile(r"\bSuper Bowl\b", re.IGNORECASE), "Super Bowl"),
    (re.compile(r"\bWorld Series\b", re.IGNORECASE), "World Series"),
    (re.compile(r"\bNBA Finals\b", re.IGNORECASE), "NBA Finals"),
    (re.compile(r"\bStanley Cup\b", re.IGNORECASE), "Stanley Cup"),
    (re.compile(r"\bMarch Madness\b", re.IGNORECASE), "NCAA Tournament"),
    (re.compile(r"\bFinal Four\b", re.IGNORECASE), "NCAA Final Four"),
    (re.compile(r"\bCFP\b"), "College Football Playoff"),
    (re.compile(r"\bWrestleMania\b", re.IGNORECASE), "WrestleMania"),
    (re.compile(r"\bUFC\b"), "Ultimate Fighting Championship"),
    (re.compile(r"\bF1\b(?!\s+(?:visa|key))", re.IGNORECASE), "Formula 1"),
    (re.compile(r"\bFormula One\b", re.IGNORECASE), "Formula 1"),

    # ========================================================================
    #  Boxing / MMA
    # ========================================================================

    (re.compile(r"\bCanelo\b", re.IGNORECASE), "Canelo Alvarez"),
    (re.compile(r"\bMcGregor\b(?!\s+(?:Industries))", re.IGNORECASE), "Conor McGregor"),

    # ========================================================================
    #  Generic cross-platform normalization
    # ========================================================================

    # "to win" / "winner of" normalization
    (re.compile(r"\bto win\b", re.IGNORECASE), "winner"),
    (re.compile(r"\bwinner of the\b", re.IGNORECASE), "winner"),
    (re.compile(r"\bwinner of\b", re.IGNORECASE), "winner"),
    (re.compile(r"\bwill win\b", re.IGNORECASE), "winner"),

    # Season / year normalization
    (re.compile(r"\b2024-25\b"), "2025"),
    (re.compile(r"\b2025-26\b"), "2026"),
    (re.compile(r"\b2026-27\b"), "2027"),
    (re.compile(r"\b24/25\b"), "2025"),
    (re.compile(r"\b25/26\b"), "2026"),
    (re.compile(r"\b26/27\b"), "2027"),

    # League name normalization
    (re.compile(r"\bEnglish Premier League\b", re.IGNORECASE), "EPL"),
    (re.compile(r"\bBarclays Premier League\b", re.IGNORECASE), "EPL"),
    (re.compile(r"\bPremier League\b", re.IGNORECASE), "EPL"),
    (re.compile(r"\bUEFA Champions League\b", re.IGNORECASE), "UCL"),
    (re.compile(r"\bChampions League\b", re.IGNORECASE), "UCL"),
    (re.compile(r"\bUEFA Europa League\b", re.IGNORECASE), "UEL"),
    (re.compile(r"\bEuropa League\b", re.IGNORECASE), "UEL"),
    (re.compile(r"\bMajor League Soccer\b", re.IGNORECASE), "MLS"),
    (re.compile(r"\bNational Football League\b", re.IGNORECASE), "NFL"),
    (re.compile(r"\bNational Basketball Association\b", re.IGNORECASE), "NBA"),
    (re.compile(r"\bNational Hockey League\b", re.IGNORECASE), "NHL"),
    (re.compile(r"\bMajor League Baseball\b", re.IGNORECASE), "MLB"),
]
